project:
  type: website
  output-dir: docs

website:
  title: "stocks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: charts.qmd
        text: Charts
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



